name:                hsmodetweaks
version:             0.1.0.0
synopsis:            Tool for generating .dir-locals.el for intero
description:         Keeps .dir-locals.el up to date so that intero can
                     automatically choose the right targets
homepage:            https://github.com/mwotton/scriptable/#hsmodetweaks
license:             BSD3
author:              mwotton@gmail.com
maintainer:          mwotton@gmail.com
copyright:           2018 Mark Wotton
category:            Tools
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - directory
  - hpack >= 0.25
  - protolude
  - text
executables:
  hsmodetweaks:
    source-dirs:      app
    main:             Main.hs
